// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIPbGenesisResponse api pb genesis response
//
// swagger:model api_pbGenesisResponse
type APIPbGenesisResponse struct {

	// app hash
	AppHash string `json:"app_hash,omitempty"`

	// app state
	AppState interface{} `json:"app_state,omitempty"`

	// chain id
	ChainID string `json:"chain_id,omitempty"`

	// consensus params
	ConsensusParams *GenesisResponseConsensusParams `json:"consensus_params,omitempty"`

	// genesis time
	GenesisTime string `json:"genesis_time,omitempty"`
}

// Validate validates this api pb genesis response
func (m *APIPbGenesisResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConsensusParams(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIPbGenesisResponse) validateConsensusParams(formats strfmt.Registry) error {

	if swag.IsZero(m.ConsensusParams) { // not required
		return nil
	}

	if m.ConsensusParams != nil {
		if err := m.ConsensusParams.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("consensus_params")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIPbGenesisResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPbGenesisResponse) UnmarshalBinary(b []byte) error {
	var res APIPbGenesisResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
