// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppStateAccount app state account
//
// swagger:model AppStateAccount
type AppStateAccount struct {

	// address
	Address string `json:"address,omitempty"`

	// balance
	Balance []*AccountBalance `json:"balance"`

	// multisig data
	MultisigData *AccountMultisigData `json:"multisig_data,omitempty"`

	// nonce
	Nonce string `json:"nonce,omitempty"`
}

// Validate validates this app state account
func (m *AppStateAccount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMultisigData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppStateAccount) validateBalance(formats strfmt.Registry) error {

	if swag.IsZero(m.Balance) { // not required
		return nil
	}

	for i := 0; i < len(m.Balance); i++ {
		if swag.IsZero(m.Balance[i]) { // not required
			continue
		}

		if m.Balance[i] != nil {
			if err := m.Balance[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("balance" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AppStateAccount) validateMultisigData(formats strfmt.Registry) error {

	if swag.IsZero(m.MultisigData) { // not required
		return nil
	}

	if m.MultisigData != nil {
		if err := m.MultisigData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("multisig_data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppStateAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppStateAccount) UnmarshalBinary(b []byte) error {
	var res AppStateAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
