// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppStateFrozenFund app state frozen fund
//
// swagger:model AppStateFrozenFund
type AppStateFrozenFund struct {

	// address
	Address string `json:"address,omitempty"`

	// candidate id
	CandidateID uint64 `json:"candidate_id,omitempty,string"`

	// candidate key
	CandidateKey string `json:"candidate_key,omitempty"`

	// coin
	Coin uint64 `json:"coin,omitempty,string"`

	// height
	Height uint64 `json:"height,omitempty,string"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this app state frozen fund
func (m *AppStateFrozenFund) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app state frozen fund based on context it is used
func (m *AppStateFrozenFund) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppStateFrozenFund) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppStateFrozenFund) UnmarshalBinary(b []byte) error {
	var res AppStateFrozenFund
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
