// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppStateHaltBlock app state halt block
//
// swagger:model AppStateHaltBlock
type AppStateHaltBlock struct {

	// candidate key
	CandidateKey string `json:"candidate_key,omitempty"`

	// height
	Height string `json:"height,omitempty"`
}

// Validate validates this app state halt block
func (m *AppStateHaltBlock) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppStateHaltBlock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppStateHaltBlock) UnmarshalBinary(b []byte) error {
	var res AppStateHaltBlock
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
