// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppStateDeletedCandidate app state deleted candidate
//
// swagger:model AppStateDeletedCandidate
type AppStateDeletedCandidate struct {

	// id
	ID uint64 `json:"id,omitempty,string"`

	// public key
	PublicKey string `json:"public_key,omitempty"`
}

// Validate validates this app state deleted candidate
func (m *AppStateDeletedCandidate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app state deleted candidate based on context it is used
func (m *AppStateDeletedCandidate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppStateDeletedCandidate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppStateDeletedCandidate) UnmarshalBinary(b []byte) error {
	var res AppStateDeletedCandidate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
