// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CandidateResponseStake candidate response stake
//
// swagger:model CandidateResponseStake
type CandidateResponseStake struct {

	// bip value
	BipValue string `json:"bip_value,omitempty"`

	// coin
	Coin *APIPbCoin `json:"coin,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this candidate response stake
func (m *CandidateResponseStake) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CandidateResponseStake) validateCoin(formats strfmt.Registry) error {

	if swag.IsZero(m.Coin) { // not required
		return nil
	}

	if m.Coin != nil {
		if err := m.Coin.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coin")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CandidateResponseStake) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CandidateResponseStake) UnmarshalBinary(b []byte) error {
	var res CandidateResponseStake
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
