// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CandidatesResponse candidates response
//
// swagger:model CandidatesResponse
type CandidatesResponse struct {

	// candidates
	Candidates []*CandidateResponse `json:"candidates"`
}

// Validate validates this candidates response
func (m *CandidatesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCandidates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CandidatesResponse) validateCandidates(formats strfmt.Registry) error {

	if swag.IsZero(m.Candidates) { // not required
		return nil
	}

	for i := 0; i < len(m.Candidates); i++ {
		if swag.IsZero(m.Candidates[i]) { // not required
			continue
		}

		if m.Candidates[i] != nil {
			if err := m.Candidates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("candidates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CandidatesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CandidatesResponse) UnmarshalBinary(b []byte) error {
	var res CandidatesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
