// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FrozenResponse frozen response
//
// swagger:model FrozenResponse
type FrozenResponse struct {

	// frozen
	Frozen []*FrozenResponseFrozen `json:"frozen"`
}

// Validate validates this frozen response
func (m *FrozenResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFrozen(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FrozenResponse) validateFrozen(formats strfmt.Registry) error {
	if swag.IsZero(m.Frozen) { // not required
		return nil
	}

	for i := 0; i < len(m.Frozen); i++ {
		if swag.IsZero(m.Frozen[i]) { // not required
			continue
		}

		if m.Frozen[i] != nil {
			if err := m.Frozen[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("frozen" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this frozen response based on the context it is used
func (m *FrozenResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFrozen(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FrozenResponse) contextValidateFrozen(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Frozen); i++ {

		if m.Frozen[i] != nil {
			if err := m.Frozen[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("frozen" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *FrozenResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FrozenResponse) UnmarshalBinary(b []byte) error {
	var res FrozenResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
