// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MinGasPriceResponse min gas price response
//
// swagger:model MinGasPriceResponse
type MinGasPriceResponse struct {

	// min gas price
	MinGasPrice string `json:"min_gas_price,omitempty"`
}

// Validate validates this min gas price response
func (m *MinGasPriceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MinGasPriceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MinGasPriceResponse) UnmarshalBinary(b []byte) error {
	var res MinGasPriceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
