// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PoolOrder pool order
//
// swagger:model PoolOrder
type PoolOrder struct {

	// height
	Height uint64 `json:"height,omitempty,string"`

	// id
	ID uint64 `json:"id,omitempty,string"`

	// is sale
	IsSale bool `json:"is_sale,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`

	// volume0
	Volume0 string `json:"volume0,omitempty"`

	// volume1
	Volume1 string `json:"volume1,omitempty"`
}

// Validate validates this pool order
func (m *PoolOrder) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pool order based on context it is used
func (m *PoolOrder) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PoolOrder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoolOrder) UnmarshalBinary(b []byte) error {
	var res PoolOrder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
