// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PriceVotesResponse price votes response
//
// swagger:model PriceVotesResponse
type PriceVotesResponse struct {

	// price votes
	PriceVotes []*PriceVotesResponseVote `json:"price_votes"`
}

// Validate validates this price votes response
func (m *PriceVotesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePriceVotes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PriceVotesResponse) validatePriceVotes(formats strfmt.Registry) error {

	if swag.IsZero(m.PriceVotes) { // not required
		return nil
	}

	for i := 0; i < len(m.PriceVotes); i++ {
		if swag.IsZero(m.PriceVotes[i]) { // not required
			continue
		}

		if m.PriceVotes[i] != nil {
			if err := m.PriceVotes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("price_votes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PriceVotesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PriceVotesResponse) UnmarshalBinary(b []byte) error {
	var res PriceVotesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
