// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateVotesResponseVote update votes response vote
//
// swagger:model UpdateVotesResponseVote
type UpdateVotesResponseVote struct {

	// public keys
	PublicKeys []string `json:"public_keys"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this update votes response vote
func (m *UpdateVotesResponseVote) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateVotesResponseVote) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateVotesResponseVote) UnmarshalBinary(b []byte) error {
	var res UpdateVotesResponseVote
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
