// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIServiceMinGasPriceParams creates a new APIServiceMinGasPriceParams object
// with the default values initialized.
func NewAPIServiceMinGasPriceParams() *APIServiceMinGasPriceParams {

	return &APIServiceMinGasPriceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceMinGasPriceParamsWithTimeout creates a new APIServiceMinGasPriceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceMinGasPriceParamsWithTimeout(timeout time.Duration) *APIServiceMinGasPriceParams {

	return &APIServiceMinGasPriceParams{

		timeout: timeout,
	}
}

// NewAPIServiceMinGasPriceParamsWithContext creates a new APIServiceMinGasPriceParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceMinGasPriceParamsWithContext(ctx context.Context) *APIServiceMinGasPriceParams {

	return &APIServiceMinGasPriceParams{

		Context: ctx,
	}
}

// NewAPIServiceMinGasPriceParamsWithHTTPClient creates a new APIServiceMinGasPriceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceMinGasPriceParamsWithHTTPClient(client *http.Client) *APIServiceMinGasPriceParams {

	return &APIServiceMinGasPriceParams{
		HTTPClient: client,
	}
}

/*APIServiceMinGasPriceParams contains all the parameters to send to the API endpoint
for the Api service min gas price operation typically these are written to a http.Request
*/
type APIServiceMinGasPriceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service min gas price params
func (o *APIServiceMinGasPriceParams) WithTimeout(timeout time.Duration) *APIServiceMinGasPriceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service min gas price params
func (o *APIServiceMinGasPriceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service min gas price params
func (o *APIServiceMinGasPriceParams) WithContext(ctx context.Context) *APIServiceMinGasPriceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service min gas price params
func (o *APIServiceMinGasPriceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service min gas price params
func (o *APIServiceMinGasPriceParams) WithHTTPClient(client *http.Client) *APIServiceMinGasPriceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service min gas price params
func (o *APIServiceMinGasPriceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceMinGasPriceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
