// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/v2/models"
)

// NewAPIServiceSendTransaction2Params creates a new APIServiceSendTransaction2Params object
// with the default values initialized.
func NewAPIServiceSendTransaction2Params() *APIServiceSendTransaction2Params {
	var ()
	return &APIServiceSendTransaction2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceSendTransaction2ParamsWithTimeout creates a new APIServiceSendTransaction2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceSendTransaction2ParamsWithTimeout(timeout time.Duration) *APIServiceSendTransaction2Params {
	var ()
	return &APIServiceSendTransaction2Params{

		timeout: timeout,
	}
}

// NewAPIServiceSendTransaction2ParamsWithContext creates a new APIServiceSendTransaction2Params object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceSendTransaction2ParamsWithContext(ctx context.Context) *APIServiceSendTransaction2Params {
	var ()
	return &APIServiceSendTransaction2Params{

		Context: ctx,
	}
}

// NewAPIServiceSendTransaction2ParamsWithHTTPClient creates a new APIServiceSendTransaction2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceSendTransaction2ParamsWithHTTPClient(client *http.Client) *APIServiceSendTransaction2Params {
	var ()
	return &APIServiceSendTransaction2Params{
		HTTPClient: client,
	}
}

/*APIServiceSendTransaction2Params contains all the parameters to send to the API endpoint
for the Api service send transaction2 operation typically these are written to a http.Request
*/
type APIServiceSendTransaction2Params struct {

	/*Body*/
	Body *models.APIPbSendTransactionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service send transaction2 params
func (o *APIServiceSendTransaction2Params) WithTimeout(timeout time.Duration) *APIServiceSendTransaction2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service send transaction2 params
func (o *APIServiceSendTransaction2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service send transaction2 params
func (o *APIServiceSendTransaction2Params) WithContext(ctx context.Context) *APIServiceSendTransaction2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service send transaction2 params
func (o *APIServiceSendTransaction2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service send transaction2 params
func (o *APIServiceSendTransaction2Params) WithHTTPClient(client *http.Client) *APIServiceSendTransaction2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service send transaction2 params
func (o *APIServiceSendTransaction2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the Api service send transaction2 params
func (o *APIServiceSendTransaction2Params) WithBody(body *models.APIPbSendTransactionRequest) *APIServiceSendTransaction2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the Api service send transaction2 params
func (o *APIServiceSendTransaction2Params) SetBody(body *models.APIPbSendTransactionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceSendTransaction2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
