// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAPIServiceEstimateCoinSellAllParams creates a new APIServiceEstimateCoinSellAllParams object
// with the default values initialized.
func NewAPIServiceEstimateCoinSellAllParams() *APIServiceEstimateCoinSellAllParams {
	var ()
	return &APIServiceEstimateCoinSellAllParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceEstimateCoinSellAllParamsWithTimeout creates a new APIServiceEstimateCoinSellAllParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceEstimateCoinSellAllParamsWithTimeout(timeout time.Duration) *APIServiceEstimateCoinSellAllParams {
	var ()
	return &APIServiceEstimateCoinSellAllParams{

		timeout: timeout,
	}
}

// NewAPIServiceEstimateCoinSellAllParamsWithContext creates a new APIServiceEstimateCoinSellAllParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceEstimateCoinSellAllParamsWithContext(ctx context.Context) *APIServiceEstimateCoinSellAllParams {
	var ()
	return &APIServiceEstimateCoinSellAllParams{

		Context: ctx,
	}
}

// NewAPIServiceEstimateCoinSellAllParamsWithHTTPClient creates a new APIServiceEstimateCoinSellAllParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceEstimateCoinSellAllParamsWithHTTPClient(client *http.Client) *APIServiceEstimateCoinSellAllParams {
	var ()
	return &APIServiceEstimateCoinSellAllParams{
		HTTPClient: client,
	}
}

/*APIServiceEstimateCoinSellAllParams contains all the parameters to send to the API endpoint
for the Api service estimate coin sell all operation typically these are written to a http.Request
*/
type APIServiceEstimateCoinSellAllParams struct {

	/*CoinIDToBuy*/
	CoinIDToBuy *int64
	/*CoinIDToSell*/
	CoinIDToSell *int64
	/*GasPrice*/
	GasPrice *string
	/*Height*/
	Height *string
	/*ValueToSell*/
	ValueToSell *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) WithTimeout(timeout time.Duration) *APIServiceEstimateCoinSellAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) WithContext(ctx context.Context) *APIServiceEstimateCoinSellAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) WithHTTPClient(client *http.Client) *APIServiceEstimateCoinSellAllParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCoinIDToBuy adds the coinIDToBuy to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) WithCoinIDToBuy(coinIDToBuy *int64) *APIServiceEstimateCoinSellAllParams {
	o.SetCoinIDToBuy(coinIDToBuy)
	return o
}

// SetCoinIDToBuy adds the coinIdToBuy to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) SetCoinIDToBuy(coinIDToBuy *int64) {
	o.CoinIDToBuy = coinIDToBuy
}

// WithCoinIDToSell adds the coinIDToSell to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) WithCoinIDToSell(coinIDToSell *int64) *APIServiceEstimateCoinSellAllParams {
	o.SetCoinIDToSell(coinIDToSell)
	return o
}

// SetCoinIDToSell adds the coinIdToSell to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) SetCoinIDToSell(coinIDToSell *int64) {
	o.CoinIDToSell = coinIDToSell
}

// WithGasPrice adds the gasPrice to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) WithGasPrice(gasPrice *string) *APIServiceEstimateCoinSellAllParams {
	o.SetGasPrice(gasPrice)
	return o
}

// SetGasPrice adds the gasPrice to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) SetGasPrice(gasPrice *string) {
	o.GasPrice = gasPrice
}

// WithHeight adds the height to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) WithHeight(height *string) *APIServiceEstimateCoinSellAllParams {
	o.SetHeight(height)
	return o
}

// SetHeight adds the height to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) SetHeight(height *string) {
	o.Height = height
}

// WithValueToSell adds the valueToSell to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) WithValueToSell(valueToSell *string) *APIServiceEstimateCoinSellAllParams {
	o.SetValueToSell(valueToSell)
	return o
}

// SetValueToSell adds the valueToSell to the Api service estimate coin sell all params
func (o *APIServiceEstimateCoinSellAllParams) SetValueToSell(valueToSell *string) {
	o.ValueToSell = valueToSell
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceEstimateCoinSellAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CoinIDToBuy != nil {

		// query param coin_id_to_buy
		var qrCoinIDToBuy int64
		if o.CoinIDToBuy != nil {
			qrCoinIDToBuy = *o.CoinIDToBuy
		}
		qCoinIDToBuy := swag.FormatInt64(qrCoinIDToBuy)
		if qCoinIDToBuy != "" {
			if err := r.SetQueryParam("coin_id_to_buy", qCoinIDToBuy); err != nil {
				return err
			}
		}

	}

	if o.CoinIDToSell != nil {

		// query param coin_id_to_sell
		var qrCoinIDToSell int64
		if o.CoinIDToSell != nil {
			qrCoinIDToSell = *o.CoinIDToSell
		}
		qCoinIDToSell := swag.FormatInt64(qrCoinIDToSell)
		if qCoinIDToSell != "" {
			if err := r.SetQueryParam("coin_id_to_sell", qCoinIDToSell); err != nil {
				return err
			}
		}

	}

	if o.GasPrice != nil {

		// query param gas_price
		var qrGasPrice string
		if o.GasPrice != nil {
			qrGasPrice = *o.GasPrice
		}
		qGasPrice := qrGasPrice
		if qGasPrice != "" {
			if err := r.SetQueryParam("gas_price", qGasPrice); err != nil {
				return err
			}
		}

	}

	if o.Height != nil {

		// query param height
		var qrHeight string
		if o.Height != nil {
			qrHeight = *o.Height
		}
		qHeight := qrHeight
		if qHeight != "" {
			if err := r.SetQueryParam("height", qHeight); err != nil {
				return err
			}
		}

	}

	if o.ValueToSell != nil {

		// query param value_to_sell
		var qrValueToSell string
		if o.ValueToSell != nil {
			qrValueToSell = *o.ValueToSell
		}
		qValueToSell := qrValueToSell
		if qValueToSell != "" {
			if err := r.SetQueryParam("value_to_sell", qValueToSell); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
