// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIServiceSendTransactionParams creates a new APIServiceSendTransactionParams object
// with the default values initialized.
func NewAPIServiceSendTransactionParams() *APIServiceSendTransactionParams {
	var ()
	return &APIServiceSendTransactionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceSendTransactionParamsWithTimeout creates a new APIServiceSendTransactionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceSendTransactionParamsWithTimeout(timeout time.Duration) *APIServiceSendTransactionParams {
	var ()
	return &APIServiceSendTransactionParams{

		timeout: timeout,
	}
}

// NewAPIServiceSendTransactionParamsWithContext creates a new APIServiceSendTransactionParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceSendTransactionParamsWithContext(ctx context.Context) *APIServiceSendTransactionParams {
	var ()
	return &APIServiceSendTransactionParams{

		Context: ctx,
	}
}

// NewAPIServiceSendTransactionParamsWithHTTPClient creates a new APIServiceSendTransactionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceSendTransactionParamsWithHTTPClient(client *http.Client) *APIServiceSendTransactionParams {
	var ()
	return &APIServiceSendTransactionParams{
		HTTPClient: client,
	}
}

/*APIServiceSendTransactionParams contains all the parameters to send to the API endpoint
for the Api service send transaction operation typically these are written to a http.Request
*/
type APIServiceSendTransactionParams struct {

	/*Tx*/
	Tx string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service send transaction params
func (o *APIServiceSendTransactionParams) WithTimeout(timeout time.Duration) *APIServiceSendTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service send transaction params
func (o *APIServiceSendTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service send transaction params
func (o *APIServiceSendTransactionParams) WithContext(ctx context.Context) *APIServiceSendTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service send transaction params
func (o *APIServiceSendTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service send transaction params
func (o *APIServiceSendTransactionParams) WithHTTPClient(client *http.Client) *APIServiceSendTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service send transaction params
func (o *APIServiceSendTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTx adds the tx to the Api service send transaction params
func (o *APIServiceSendTransactionParams) WithTx(tx string) *APIServiceSendTransactionParams {
	o.SetTx(tx)
	return o
}

// SetTx adds the tx to the Api service send transaction params
func (o *APIServiceSendTransactionParams) SetTx(tx string) {
	o.Tx = tx
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceSendTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tx
	if err := r.SetPathParam("tx", o.Tx); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
