// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAPIServiceAddressParams creates a new APIServiceAddressParams object
// with the default values initialized.
func NewAPIServiceAddressParams() *APIServiceAddressParams {
	var ()
	return &APIServiceAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceAddressParamsWithTimeout creates a new APIServiceAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceAddressParamsWithTimeout(timeout time.Duration) *APIServiceAddressParams {
	var ()
	return &APIServiceAddressParams{

		timeout: timeout,
	}
}

// NewAPIServiceAddressParamsWithContext creates a new APIServiceAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceAddressParamsWithContext(ctx context.Context) *APIServiceAddressParams {
	var ()
	return &APIServiceAddressParams{

		Context: ctx,
	}
}

// NewAPIServiceAddressParamsWithHTTPClient creates a new APIServiceAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceAddressParamsWithHTTPClient(client *http.Client) *APIServiceAddressParams {
	var ()
	return &APIServiceAddressParams{
		HTTPClient: client,
	}
}

/*APIServiceAddressParams contains all the parameters to send to the API endpoint
for the Api service address operation typically these are written to a http.Request
*/
type APIServiceAddressParams struct {

	/*Address*/
	Address string
	/*Delegated*/
	Delegated *bool
	/*Height*/
	Height *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service address params
func (o *APIServiceAddressParams) WithTimeout(timeout time.Duration) *APIServiceAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service address params
func (o *APIServiceAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service address params
func (o *APIServiceAddressParams) WithContext(ctx context.Context) *APIServiceAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service address params
func (o *APIServiceAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service address params
func (o *APIServiceAddressParams) WithHTTPClient(client *http.Client) *APIServiceAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service address params
func (o *APIServiceAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the Api service address params
func (o *APIServiceAddressParams) WithAddress(address string) *APIServiceAddressParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the Api service address params
func (o *APIServiceAddressParams) SetAddress(address string) {
	o.Address = address
}

// WithDelegated adds the delegated to the Api service address params
func (o *APIServiceAddressParams) WithDelegated(delegated *bool) *APIServiceAddressParams {
	o.SetDelegated(delegated)
	return o
}

// SetDelegated adds the delegated to the Api service address params
func (o *APIServiceAddressParams) SetDelegated(delegated *bool) {
	o.Delegated = delegated
}

// WithHeight adds the height to the Api service address params
func (o *APIServiceAddressParams) WithHeight(height *string) *APIServiceAddressParams {
	o.SetHeight(height)
	return o
}

// SetHeight adds the height to the Api service address params
func (o *APIServiceAddressParams) SetHeight(height *string) {
	o.Height = height
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if o.Delegated != nil {

		// query param delegated
		var qrDelegated bool
		if o.Delegated != nil {
			qrDelegated = *o.Delegated
		}
		qDelegated := swag.FormatBool(qrDelegated)
		if qDelegated != "" {
			if err := r.SetQueryParam("delegated", qDelegated); err != nil {
				return err
			}
		}

	}

	if o.Height != nil {

		// query param height
		var qrHeight string
		if o.Height != nil {
			qrHeight = *o.Height
		}
		qHeight := qrHeight
		if qHeight != "" {
			if err := r.SetQueryParam("height", qHeight); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
