// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAPIServiceEstimateCoinSellParams creates a new APIServiceEstimateCoinSellParams object
// with the default values initialized.
func NewAPIServiceEstimateCoinSellParams() *APIServiceEstimateCoinSellParams {
	var ()
	return &APIServiceEstimateCoinSellParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceEstimateCoinSellParamsWithTimeout creates a new APIServiceEstimateCoinSellParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceEstimateCoinSellParamsWithTimeout(timeout time.Duration) *APIServiceEstimateCoinSellParams {
	var ()
	return &APIServiceEstimateCoinSellParams{

		timeout: timeout,
	}
}

// NewAPIServiceEstimateCoinSellParamsWithContext creates a new APIServiceEstimateCoinSellParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceEstimateCoinSellParamsWithContext(ctx context.Context) *APIServiceEstimateCoinSellParams {
	var ()
	return &APIServiceEstimateCoinSellParams{

		Context: ctx,
	}
}

// NewAPIServiceEstimateCoinSellParamsWithHTTPClient creates a new APIServiceEstimateCoinSellParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceEstimateCoinSellParamsWithHTTPClient(client *http.Client) *APIServiceEstimateCoinSellParams {
	var ()
	return &APIServiceEstimateCoinSellParams{
		HTTPClient: client,
	}
}

/*APIServiceEstimateCoinSellParams contains all the parameters to send to the API endpoint
for the Api service estimate coin sell operation typically these are written to a http.Request
*/
type APIServiceEstimateCoinSellParams struct {

	/*CoinIDToBuy*/
	CoinIDToBuy *int64
	/*CoinIDToSell*/
	CoinIDToSell *int64
	/*Height*/
	Height *string
	/*ValueToSell*/
	ValueToSell *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) WithTimeout(timeout time.Duration) *APIServiceEstimateCoinSellParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) WithContext(ctx context.Context) *APIServiceEstimateCoinSellParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) WithHTTPClient(client *http.Client) *APIServiceEstimateCoinSellParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCoinIDToBuy adds the coinIDToBuy to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) WithCoinIDToBuy(coinIDToBuy *int64) *APIServiceEstimateCoinSellParams {
	o.SetCoinIDToBuy(coinIDToBuy)
	return o
}

// SetCoinIDToBuy adds the coinIdToBuy to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) SetCoinIDToBuy(coinIDToBuy *int64) {
	o.CoinIDToBuy = coinIDToBuy
}

// WithCoinIDToSell adds the coinIDToSell to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) WithCoinIDToSell(coinIDToSell *int64) *APIServiceEstimateCoinSellParams {
	o.SetCoinIDToSell(coinIDToSell)
	return o
}

// SetCoinIDToSell adds the coinIdToSell to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) SetCoinIDToSell(coinIDToSell *int64) {
	o.CoinIDToSell = coinIDToSell
}

// WithHeight adds the height to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) WithHeight(height *string) *APIServiceEstimateCoinSellParams {
	o.SetHeight(height)
	return o
}

// SetHeight adds the height to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) SetHeight(height *string) {
	o.Height = height
}

// WithValueToSell adds the valueToSell to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) WithValueToSell(valueToSell *string) *APIServiceEstimateCoinSellParams {
	o.SetValueToSell(valueToSell)
	return o
}

// SetValueToSell adds the valueToSell to the Api service estimate coin sell params
func (o *APIServiceEstimateCoinSellParams) SetValueToSell(valueToSell *string) {
	o.ValueToSell = valueToSell
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceEstimateCoinSellParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CoinIDToBuy != nil {

		// query param coin_id_to_buy
		var qrCoinIDToBuy int64
		if o.CoinIDToBuy != nil {
			qrCoinIDToBuy = *o.CoinIDToBuy
		}
		qCoinIDToBuy := swag.FormatInt64(qrCoinIDToBuy)
		if qCoinIDToBuy != "" {
			if err := r.SetQueryParam("coin_id_to_buy", qCoinIDToBuy); err != nil {
				return err
			}
		}

	}

	if o.CoinIDToSell != nil {

		// query param coin_id_to_sell
		var qrCoinIDToSell int64
		if o.CoinIDToSell != nil {
			qrCoinIDToSell = *o.CoinIDToSell
		}
		qCoinIDToSell := swag.FormatInt64(qrCoinIDToSell)
		if qCoinIDToSell != "" {
			if err := r.SetQueryParam("coin_id_to_sell", qCoinIDToSell); err != nil {
				return err
			}
		}

	}

	if o.Height != nil {

		// query param height
		var qrHeight string
		if o.Height != nil {
			qrHeight = *o.Height
		}
		qHeight := qrHeight
		if qHeight != "" {
			if err := r.SetQueryParam("height", qHeight); err != nil {
				return err
			}
		}

	}

	if o.ValueToSell != nil {

		// query param value_to_sell
		var qrValueToSell string
		if o.ValueToSell != nil {
			qrValueToSell = *o.ValueToSell
		}
		qValueToSell := qrValueToSell
		if qValueToSell != "" {
			if err := r.SetQueryParam("value_to_sell", qValueToSell); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
