// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/v2/models"
)

// APIServiceMinGasPriceReader is a Reader for the APIServiceMinGasPrice structure.
type APIServiceMinGasPriceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIServiceMinGasPriceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPIServiceMinGasPriceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAPIServiceMinGasPriceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAPIServiceMinGasPriceOK creates a APIServiceMinGasPriceOK with default headers values
func NewAPIServiceMinGasPriceOK() *APIServiceMinGasPriceOK {
	return &APIServiceMinGasPriceOK{}
}

/*APIServiceMinGasPriceOK handles this case with default header values.

A successful response.
*/
type APIServiceMinGasPriceOK struct {
	Payload *models.APIPbMinGasPriceResponse
}

func (o *APIServiceMinGasPriceOK) Error() string {
	return fmt.Sprintf("[GET /min_gas_price][%d] apiServiceMinGasPriceOK  %+v", 200, o.Payload)
}

func (o *APIServiceMinGasPriceOK) GetPayload() *models.APIPbMinGasPriceResponse {
	return o.Payload
}

func (o *APIServiceMinGasPriceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIPbMinGasPriceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIServiceMinGasPriceDefault creates a APIServiceMinGasPriceDefault with default headers values
func NewAPIServiceMinGasPriceDefault(code int) *APIServiceMinGasPriceDefault {
	return &APIServiceMinGasPriceDefault{
		_statusCode: code,
	}
}

/*APIServiceMinGasPriceDefault handles this case with default header values.

An unexpected error response
*/
type APIServiceMinGasPriceDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the Api service min gas price default response
func (o *APIServiceMinGasPriceDefault) Code() int {
	return o._statusCode
}

func (o *APIServiceMinGasPriceDefault) Error() string {
	return fmt.Sprintf("[GET /min_gas_price][%d] ApiService_MinGasPrice default  %+v", o._statusCode, o.Payload)
}

func (o *APIServiceMinGasPriceDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *APIServiceMinGasPriceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
