// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/v2/models"
)

// APIServiceTransactionsReader is a Reader for the APIServiceTransactions structure.
type APIServiceTransactionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIServiceTransactionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPIServiceTransactionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAPIServiceTransactionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAPIServiceTransactionsOK creates a APIServiceTransactionsOK with default headers values
func NewAPIServiceTransactionsOK() *APIServiceTransactionsOK {
	return &APIServiceTransactionsOK{}
}

/*APIServiceTransactionsOK handles this case with default header values.

A successful response.
*/
type APIServiceTransactionsOK struct {
	Payload *models.APIPbTransactionsResponse
}

func (o *APIServiceTransactionsOK) Error() string {
	return fmt.Sprintf("[GET /transactions][%d] apiServiceTransactionsOK  %+v", 200, o.Payload)
}

func (o *APIServiceTransactionsOK) GetPayload() *models.APIPbTransactionsResponse {
	return o.Payload
}

func (o *APIServiceTransactionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIPbTransactionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIServiceTransactionsDefault creates a APIServiceTransactionsDefault with default headers values
func NewAPIServiceTransactionsDefault(code int) *APIServiceTransactionsDefault {
	return &APIServiceTransactionsDefault{
		_statusCode: code,
	}
}

/*APIServiceTransactionsDefault handles this case with default header values.

An unexpected error response
*/
type APIServiceTransactionsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the Api service transactions default response
func (o *APIServiceTransactionsDefault) Code() int {
	return o._statusCode
}

func (o *APIServiceTransactionsDefault) Error() string {
	return fmt.Sprintf("[GET /transactions][%d] ApiService_Transactions default  %+v", o._statusCode, o.Payload)
}

func (o *APIServiceTransactionsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *APIServiceTransactionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
