// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIPbSubscribeResponseEvent api pb subscribe response event
//
// swagger:model api_pbSubscribeResponseEvent
type APIPbSubscribeResponseEvent struct {

	// events
	Events []string `json:"events"`

	// key
	Key string `json:"key,omitempty"`
}

// Validate validates this api pb subscribe response event
func (m *APIPbSubscribeResponseEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIPbSubscribeResponseEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPbSubscribeResponseEvent) UnmarshalBinary(b []byte) error {
	var res APIPbSubscribeResponseEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
