// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIPbEstimateCoinBuyResponse api pb estimate coin buy response
//
// swagger:model api_pbEstimateCoinBuyResponse
type APIPbEstimateCoinBuyResponse struct {

	// commission
	Commission string `json:"commission,omitempty"`

	// will pay
	WillPay string `json:"will_pay,omitempty"`
}

// Validate validates this api pb estimate coin buy response
func (m *APIPbEstimateCoinBuyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIPbEstimateCoinBuyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPbEstimateCoinBuyResponse) UnmarshalBinary(b []byte) error {
	var res APIPbEstimateCoinBuyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
