// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIServiceStatusParams creates a new APIServiceStatusParams object
// with the default values initialized.
func NewAPIServiceStatusParams() *APIServiceStatusParams {

	return &APIServiceStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceStatusParamsWithTimeout creates a new APIServiceStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceStatusParamsWithTimeout(timeout time.Duration) *APIServiceStatusParams {

	return &APIServiceStatusParams{

		timeout: timeout,
	}
}

// NewAPIServiceStatusParamsWithContext creates a new APIServiceStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceStatusParamsWithContext(ctx context.Context) *APIServiceStatusParams {

	return &APIServiceStatusParams{

		Context: ctx,
	}
}

// NewAPIServiceStatusParamsWithHTTPClient creates a new APIServiceStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceStatusParamsWithHTTPClient(client *http.Client) *APIServiceStatusParams {

	return &APIServiceStatusParams{
		HTTPClient: client,
	}
}

/*APIServiceStatusParams contains all the parameters to send to the API endpoint
for the Api service status operation typically these are written to a http.Request
*/
type APIServiceStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service status params
func (o *APIServiceStatusParams) WithTimeout(timeout time.Duration) *APIServiceStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service status params
func (o *APIServiceStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service status params
func (o *APIServiceStatusParams) WithContext(ctx context.Context) *APIServiceStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service status params
func (o *APIServiceStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service status params
func (o *APIServiceStatusParams) WithHTTPClient(client *http.Client) *APIServiceStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service status params
func (o *APIServiceStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
