// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// BlockReader is a Reader for the Block structure.
type BlockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BlockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBlockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewBlockDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBlockOK creates a BlockOK with default headers values
func NewBlockOK() *BlockOK {
	return &BlockOK{}
}

/* BlockOK describes a response with status code 200, with default header values.

A successful response.
*/
type BlockOK struct {
	Payload *models.BlockResponse
}

func (o *BlockOK) Error() string {
	return fmt.Sprintf("[GET /block/{height}][%d] blockOK  %+v", 200, o.Payload)
}
func (o *BlockOK) GetPayload() *models.BlockResponse {
	return o.Payload
}

func (o *BlockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BlockResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBlockDefault creates a BlockDefault with default headers values
func NewBlockDefault(code int) *BlockDefault {
	return &BlockDefault{
		_statusCode: code,
	}
}

/* BlockDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type BlockDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the block default response
func (o *BlockDefault) Code() int {
	return o._statusCode
}

func (o *BlockDefault) Error() string {
	return fmt.Sprintf("[GET /block/{height}][%d] Block default  %+v", o._statusCode, o.Payload)
}
func (o *BlockDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *BlockDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
