// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// CoinInfoByIDReader is a Reader for the CoinInfoByID structure.
type CoinInfoByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CoinInfoByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCoinInfoByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCoinInfoByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCoinInfoByIDOK creates a CoinInfoByIDOK with default headers values
func NewCoinInfoByIDOK() *CoinInfoByIDOK {
	return &CoinInfoByIDOK{}
}

/*CoinInfoByIDOK handles this case with default header values.

A successful response.
*/
type CoinInfoByIDOK struct {
	Payload *models.CoinInfoResponse
}

func (o *CoinInfoByIDOK) Error() string {
	return fmt.Sprintf("[GET /coin_info_by_id/{id}][%d] coinInfoByIdOK  %+v", 200, o.Payload)
}

func (o *CoinInfoByIDOK) GetPayload() *models.CoinInfoResponse {
	return o.Payload
}

func (o *CoinInfoByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoinInfoResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCoinInfoByIDDefault creates a CoinInfoByIDDefault with default headers values
func NewCoinInfoByIDDefault(code int) *CoinInfoByIDDefault {
	return &CoinInfoByIDDefault{
		_statusCode: code,
	}
}

/*CoinInfoByIDDefault handles this case with default header values.

An unexpected error response
*/
type CoinInfoByIDDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the coin info by Id default response
func (o *CoinInfoByIDDefault) Code() int {
	return o._statusCode
}

func (o *CoinInfoByIDDefault) Error() string {
	return fmt.Sprintf("[GET /coin_info_by_id/{id}][%d] CoinInfoById default  %+v", o._statusCode, o.Payload)
}

func (o *CoinInfoByIDDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *CoinInfoByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
