// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// EstimateCoinSellReader is a Reader for the EstimateCoinSell structure.
type EstimateCoinSellReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EstimateCoinSellReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEstimateCoinSellOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEstimateCoinSellDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEstimateCoinSellOK creates a EstimateCoinSellOK with default headers values
func NewEstimateCoinSellOK() *EstimateCoinSellOK {
	return &EstimateCoinSellOK{}
}

/* EstimateCoinSellOK describes a response with status code 200, with default header values.

A successful response.
*/
type EstimateCoinSellOK struct {
	Payload *models.EstimateCoinSellResponse
}

func (o *EstimateCoinSellOK) Error() string {
	return fmt.Sprintf("[GET /estimate_coin_sell][%d] estimateCoinSellOK  %+v", 200, o.Payload)
}
func (o *EstimateCoinSellOK) GetPayload() *models.EstimateCoinSellResponse {
	return o.Payload
}

func (o *EstimateCoinSellOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EstimateCoinSellResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEstimateCoinSellDefault creates a EstimateCoinSellDefault with default headers values
func NewEstimateCoinSellDefault(code int) *EstimateCoinSellDefault {
	return &EstimateCoinSellDefault{
		_statusCode: code,
	}
}

/* EstimateCoinSellDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EstimateCoinSellDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the estimate coin sell default response
func (o *EstimateCoinSellDefault) Code() int {
	return o._statusCode
}

func (o *EstimateCoinSellDefault) Error() string {
	return fmt.Sprintf("[GET /estimate_coin_sell][%d] EstimateCoinSell default  %+v", o._statusCode, o.Payload)
}
func (o *EstimateCoinSellDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *EstimateCoinSellDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
