// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// EstimateCoinSellAllReader is a Reader for the EstimateCoinSellAll structure.
type EstimateCoinSellAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EstimateCoinSellAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEstimateCoinSellAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEstimateCoinSellAllDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEstimateCoinSellAllOK creates a EstimateCoinSellAllOK with default headers values
func NewEstimateCoinSellAllOK() *EstimateCoinSellAllOK {
	return &EstimateCoinSellAllOK{}
}

/*EstimateCoinSellAllOK handles this case with default header values.

A successful response.
*/
type EstimateCoinSellAllOK struct {
	Payload *models.EstimateCoinSellAllResponse
}

func (o *EstimateCoinSellAllOK) Error() string {
	return fmt.Sprintf("[GET /estimate_coin_sell_all][%d] estimateCoinSellAllOK  %+v", 200, o.Payload)
}

func (o *EstimateCoinSellAllOK) GetPayload() *models.EstimateCoinSellAllResponse {
	return o.Payload
}

func (o *EstimateCoinSellAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EstimateCoinSellAllResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEstimateCoinSellAllDefault creates a EstimateCoinSellAllDefault with default headers values
func NewEstimateCoinSellAllDefault(code int) *EstimateCoinSellAllDefault {
	return &EstimateCoinSellAllDefault{
		_statusCode: code,
	}
}

/*EstimateCoinSellAllDefault handles this case with default header values.

An unexpected error response
*/
type EstimateCoinSellAllDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the estimate coin sell all default response
func (o *EstimateCoinSellAllDefault) Code() int {
	return o._statusCode
}

func (o *EstimateCoinSellAllDefault) Error() string {
	return fmt.Sprintf("[GET /estimate_coin_sell_all][%d] EstimateCoinSellAll default  %+v", o._statusCode, o.Payload)
}

func (o *EstimateCoinSellAllDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *EstimateCoinSellAllDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
