// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLimitOrderParams creates a new LimitOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLimitOrderParams() *LimitOrderParams {
	return &LimitOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLimitOrderParamsWithTimeout creates a new LimitOrderParams object
// with the ability to set a timeout on a request.
func NewLimitOrderParamsWithTimeout(timeout time.Duration) *LimitOrderParams {
	return &LimitOrderParams{
		timeout: timeout,
	}
}

// NewLimitOrderParamsWithContext creates a new LimitOrderParams object
// with the ability to set a context for a request.
func NewLimitOrderParamsWithContext(ctx context.Context) *LimitOrderParams {
	return &LimitOrderParams{
		Context: ctx,
	}
}

// NewLimitOrderParamsWithHTTPClient creates a new LimitOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewLimitOrderParamsWithHTTPClient(client *http.Client) *LimitOrderParams {
	return &LimitOrderParams{
		HTTPClient: client,
	}
}

/* LimitOrderParams contains all the parameters to send to the API endpoint
   for the limit order operation.

   Typically these are written to a http.Request.
*/
type LimitOrderParams struct {

	// Height.
	//
	// Format: uint64
	Height *uint64

	// OrderID.
	//
	// Format: uint64
	OrderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the limit order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LimitOrderParams) WithDefaults() *LimitOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the limit order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LimitOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the limit order params
func (o *LimitOrderParams) WithTimeout(timeout time.Duration) *LimitOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the limit order params
func (o *LimitOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the limit order params
func (o *LimitOrderParams) WithContext(ctx context.Context) *LimitOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the limit order params
func (o *LimitOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the limit order params
func (o *LimitOrderParams) WithHTTPClient(client *http.Client) *LimitOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the limit order params
func (o *LimitOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeight adds the height to the limit order params
func (o *LimitOrderParams) WithHeight(height *uint64) *LimitOrderParams {
	o.SetHeight(height)
	return o
}

// SetHeight adds the height to the limit order params
func (o *LimitOrderParams) SetHeight(height *uint64) {
	o.Height = height
}

// WithOrderID adds the orderID to the limit order params
func (o *LimitOrderParams) WithOrderID(orderID string) *LimitOrderParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the limit order params
func (o *LimitOrderParams) SetOrderID(orderID string) {
	o.OrderID = orderID
}

// WriteToRequest writes these params to a swagger request
func (o *LimitOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Height != nil {

		// query param height
		var qrHeight uint64

		if o.Height != nil {
			qrHeight = *o.Height
		}
		qHeight := swag.FormatUint64(qrHeight)
		if qHeight != "" {

			if err := r.SetQueryParam("height", qHeight); err != nil {
				return err
			}
		}
	}

	// path param order_id
	if err := r.SetPathParam("order_id", o.OrderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
