// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMaxGasParams creates a new MaxGasParams object
// with the default values initialized.
func NewMaxGasParams() *MaxGasParams {
	var ()
	return &MaxGasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMaxGasParamsWithTimeout creates a new MaxGasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMaxGasParamsWithTimeout(timeout time.Duration) *MaxGasParams {
	var ()
	return &MaxGasParams{

		timeout: timeout,
	}
}

// NewMaxGasParamsWithContext creates a new MaxGasParams object
// with the default values initialized, and the ability to set a context for a request
func NewMaxGasParamsWithContext(ctx context.Context) *MaxGasParams {
	var ()
	return &MaxGasParams{

		Context: ctx,
	}
}

// NewMaxGasParamsWithHTTPClient creates a new MaxGasParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMaxGasParamsWithHTTPClient(client *http.Client) *MaxGasParams {
	var ()
	return &MaxGasParams{
		HTTPClient: client,
	}
}

/*MaxGasParams contains all the parameters to send to the API endpoint
for the max gas operation typically these are written to a http.Request
*/
type MaxGasParams struct {

	/*Height*/
	Height *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the max gas params
func (o *MaxGasParams) WithTimeout(timeout time.Duration) *MaxGasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the max gas params
func (o *MaxGasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the max gas params
func (o *MaxGasParams) WithContext(ctx context.Context) *MaxGasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the max gas params
func (o *MaxGasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the max gas params
func (o *MaxGasParams) WithHTTPClient(client *http.Client) *MaxGasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the max gas params
func (o *MaxGasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeight adds the height to the max gas params
func (o *MaxGasParams) WithHeight(height *string) *MaxGasParams {
	o.SetHeight(height)
	return o
}

// SetHeight adds the height to the max gas params
func (o *MaxGasParams) SetHeight(height *string) {
	o.Height = height
}

// WriteToRequest writes these params to a swagger request
func (o *MaxGasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Height != nil {

		// query param height
		var qrHeight string
		if o.Height != nil {
			qrHeight = *o.Height
		}
		qHeight := qrHeight
		if qHeight != "" {
			if err := r.SetQueryParam("height", qHeight); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
