// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// MinGasPriceReader is a Reader for the MinGasPrice structure.
type MinGasPriceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MinGasPriceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMinGasPriceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewMinGasPriceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMinGasPriceOK creates a MinGasPriceOK with default headers values
func NewMinGasPriceOK() *MinGasPriceOK {
	return &MinGasPriceOK{}
}

/* MinGasPriceOK describes a response with status code 200, with default header values.

A successful response.
*/
type MinGasPriceOK struct {
	Payload *models.MinGasPriceResponse
}

func (o *MinGasPriceOK) Error() string {
	return fmt.Sprintf("[GET /min_gas_price][%d] minGasPriceOK  %+v", 200, o.Payload)
}
func (o *MinGasPriceOK) GetPayload() *models.MinGasPriceResponse {
	return o.Payload
}

func (o *MinGasPriceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MinGasPriceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMinGasPriceDefault creates a MinGasPriceDefault with default headers values
func NewMinGasPriceDefault(code int) *MinGasPriceDefault {
	return &MinGasPriceDefault{
		_statusCode: code,
	}
}

/* MinGasPriceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type MinGasPriceDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the min gas price default response
func (o *MinGasPriceDefault) Code() int {
	return o._statusCode
}

func (o *MinGasPriceDefault) Error() string {
	return fmt.Sprintf("[GET /min_gas_price][%d] MinGasPrice default  %+v", o._statusCode, o.Payload)
}
func (o *MinGasPriceDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *MinGasPriceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
