// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// NetInfoReader is a Reader for the NetInfo structure.
type NetInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNetInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNetInfoDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetInfoOK creates a NetInfoOK with default headers values
func NewNetInfoOK() *NetInfoOK {
	return &NetInfoOK{}
}

/* NetInfoOK describes a response with status code 200, with default header values.

A successful response.
*/
type NetInfoOK struct {
	Payload *models.NetInfoResponse
}

func (o *NetInfoOK) Error() string {
	return fmt.Sprintf("[GET /net_info][%d] netInfoOK  %+v", 200, o.Payload)
}
func (o *NetInfoOK) GetPayload() *models.NetInfoResponse {
	return o.Payload
}

func (o *NetInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetInfoResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetInfoDefault creates a NetInfoDefault with default headers values
func NewNetInfoDefault(code int) *NetInfoDefault {
	return &NetInfoDefault{
		_statusCode: code,
	}
}

/* NetInfoDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type NetInfoDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the net info default response
func (o *NetInfoDefault) Code() int {
	return o._statusCode
}

func (o *NetInfoDefault) Error() string {
	return fmt.Sprintf("[GET /net_info][%d] NetInfo default  %+v", o._statusCode, o.Payload)
}
func (o *NetInfoDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *NetInfoDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
