// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPriceCommissionParams creates a new PriceCommissionParams object
// with the default values initialized.
func NewPriceCommissionParams() *PriceCommissionParams {
	var ()
	return &PriceCommissionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPriceCommissionParamsWithTimeout creates a new PriceCommissionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPriceCommissionParamsWithTimeout(timeout time.Duration) *PriceCommissionParams {
	var ()
	return &PriceCommissionParams{

		timeout: timeout,
	}
}

// NewPriceCommissionParamsWithContext creates a new PriceCommissionParams object
// with the default values initialized, and the ability to set a context for a request
func NewPriceCommissionParamsWithContext(ctx context.Context) *PriceCommissionParams {
	var ()
	return &PriceCommissionParams{

		Context: ctx,
	}
}

// NewPriceCommissionParamsWithHTTPClient creates a new PriceCommissionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPriceCommissionParamsWithHTTPClient(client *http.Client) *PriceCommissionParams {
	var ()
	return &PriceCommissionParams{
		HTTPClient: client,
	}
}

/*PriceCommissionParams contains all the parameters to send to the API endpoint
for the price commission operation typically these are written to a http.Request
*/
type PriceCommissionParams struct {

	/*Height*/
	Height *uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the price commission params
func (o *PriceCommissionParams) WithTimeout(timeout time.Duration) *PriceCommissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the price commission params
func (o *PriceCommissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the price commission params
func (o *PriceCommissionParams) WithContext(ctx context.Context) *PriceCommissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the price commission params
func (o *PriceCommissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the price commission params
func (o *PriceCommissionParams) WithHTTPClient(client *http.Client) *PriceCommissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the price commission params
func (o *PriceCommissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeight adds the height to the price commission params
func (o *PriceCommissionParams) WithHeight(height *uint64) *PriceCommissionParams {
	o.SetHeight(height)
	return o
}

// SetHeight adds the height to the price commission params
func (o *PriceCommissionParams) SetHeight(height *uint64) {
	o.Height = height
}

// WriteToRequest writes these params to a swagger request
func (o *PriceCommissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Height != nil {

		// query param height
		var qrHeight uint64
		if o.Height != nil {
			qrHeight = *o.Height
		}
		qHeight := swag.FormatUint64(qrHeight)
		if qHeight != "" {
			if err := r.SetQueryParam("height", qHeight); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
