// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// SendTransactionReader is a Reader for the SendTransaction structure.
type SendTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSendTransactionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSendTransactionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSendTransactionOK creates a SendTransactionOK with default headers values
func NewSendTransactionOK() *SendTransactionOK {
	return &SendTransactionOK{}
}

/*SendTransactionOK handles this case with default header values.

A successful response.
*/
type SendTransactionOK struct {
	Payload *models.SendTransactionResponse
}

func (o *SendTransactionOK) Error() string {
	return fmt.Sprintf("[GET /send_transaction/{tx}][%d] sendTransactionOK  %+v", 200, o.Payload)
}

func (o *SendTransactionOK) GetPayload() *models.SendTransactionResponse {
	return o.Payload
}

func (o *SendTransactionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SendTransactionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendTransactionDefault creates a SendTransactionDefault with default headers values
func NewSendTransactionDefault(code int) *SendTransactionDefault {
	return &SendTransactionDefault{
		_statusCode: code,
	}
}

/*SendTransactionDefault handles this case with default header values.

An unexpected error response.
*/
type SendTransactionDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the send transaction default response
func (o *SendTransactionDefault) Code() int {
	return o._statusCode
}

func (o *SendTransactionDefault) Error() string {
	return fmt.Sprintf("[GET /send_transaction/{tx}][%d] SendTransaction default  %+v", o._statusCode, o.Payload)
}

func (o *SendTransactionDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *SendTransactionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
