// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSwapPoolParams creates a new SwapPoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSwapPoolParams() *SwapPoolParams {
	return &SwapPoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSwapPoolParamsWithTimeout creates a new SwapPoolParams object
// with the ability to set a timeout on a request.
func NewSwapPoolParamsWithTimeout(timeout time.Duration) *SwapPoolParams {
	return &SwapPoolParams{
		timeout: timeout,
	}
}

// NewSwapPoolParamsWithContext creates a new SwapPoolParams object
// with the ability to set a context for a request.
func NewSwapPoolParamsWithContext(ctx context.Context) *SwapPoolParams {
	return &SwapPoolParams{
		Context: ctx,
	}
}

// NewSwapPoolParamsWithHTTPClient creates a new SwapPoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewSwapPoolParamsWithHTTPClient(client *http.Client) *SwapPoolParams {
	return &SwapPoolParams{
		HTTPClient: client,
	}
}

/* SwapPoolParams contains all the parameters to send to the API endpoint
   for the swap pool operation.

   Typically these are written to a http.Request.
*/
type SwapPoolParams struct {

	// Coin0.
	//
	// Format: uint64
	Coin0 string

	// Coin1.
	//
	// Format: uint64
	Coin1 string

	// Height.
	//
	// Format: uint64
	Height *uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the swap pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SwapPoolParams) WithDefaults() *SwapPoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the swap pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SwapPoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the swap pool params
func (o *SwapPoolParams) WithTimeout(timeout time.Duration) *SwapPoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the swap pool params
func (o *SwapPoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the swap pool params
func (o *SwapPoolParams) WithContext(ctx context.Context) *SwapPoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the swap pool params
func (o *SwapPoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the swap pool params
func (o *SwapPoolParams) WithHTTPClient(client *http.Client) *SwapPoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the swap pool params
func (o *SwapPoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCoin0 adds the coin0 to the swap pool params
func (o *SwapPoolParams) WithCoin0(coin0 string) *SwapPoolParams {
	o.SetCoin0(coin0)
	return o
}

// SetCoin0 adds the coin0 to the swap pool params
func (o *SwapPoolParams) SetCoin0(coin0 string) {
	o.Coin0 = coin0
}

// WithCoin1 adds the coin1 to the swap pool params
func (o *SwapPoolParams) WithCoin1(coin1 string) *SwapPoolParams {
	o.SetCoin1(coin1)
	return o
}

// SetCoin1 adds the coin1 to the swap pool params
func (o *SwapPoolParams) SetCoin1(coin1 string) {
	o.Coin1 = coin1
}

// WithHeight adds the height to the swap pool params
func (o *SwapPoolParams) WithHeight(height *uint64) *SwapPoolParams {
	o.SetHeight(height)
	return o
}

// SetHeight adds the height to the swap pool params
func (o *SwapPoolParams) SetHeight(height *uint64) {
	o.Height = height
}

// WriteToRequest writes these params to a swagger request
func (o *SwapPoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param coin0
	if err := r.SetPathParam("coin0", o.Coin0); err != nil {
		return err
	}

	// path param coin1
	if err := r.SetPathParam("coin1", o.Coin1); err != nil {
		return err
	}

	if o.Height != nil {

		// query param height
		var qrHeight uint64

		if o.Height != nil {
			qrHeight = *o.Height
		}
		qHeight := swag.FormatUint64(qrHeight)
		if qHeight != "" {

			if err := r.SetQueryParam("height", qHeight); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
