// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// SwapPoolReader is a Reader for the SwapPool structure.
type SwapPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SwapPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSwapPoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSwapPoolDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSwapPoolOK creates a SwapPoolOK with default headers values
func NewSwapPoolOK() *SwapPoolOK {
	return &SwapPoolOK{}
}

/* SwapPoolOK describes a response with status code 200, with default header values.

A successful response.
*/
type SwapPoolOK struct {
	Payload *models.SwapPoolResponse
}

func (o *SwapPoolOK) Error() string {
	return fmt.Sprintf("[GET /swap_pool/{coin0}/{coin1}][%d] swapPoolOK  %+v", 200, o.Payload)
}
func (o *SwapPoolOK) GetPayload() *models.SwapPoolResponse {
	return o.Payload
}

func (o *SwapPoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SwapPoolResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSwapPoolDefault creates a SwapPoolDefault with default headers values
func NewSwapPoolDefault(code int) *SwapPoolDefault {
	return &SwapPoolDefault{
		_statusCode: code,
	}
}

/* SwapPoolDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SwapPoolDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the swap pool default response
func (o *SwapPoolDefault) Code() int {
	return o._statusCode
}

func (o *SwapPoolDefault) Error() string {
	return fmt.Sprintf("[GET /swap_pool/{coin0}/{coin1}][%d] SwapPool default  %+v", o._statusCode, o.Payload)
}
func (o *SwapPoolDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *SwapPoolDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
