// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MinterTeam/minter-go-sdk/v2/api/http_client/models"
)

// TransactionReader is a Reader for the Transaction structure.
type TransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTransactionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTransactionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTransactionOK creates a TransactionOK with default headers values
func NewTransactionOK() *TransactionOK {
	return &TransactionOK{}
}

/* TransactionOK describes a response with status code 200, with default header values.

A successful response.
*/
type TransactionOK struct {
	Payload *models.TransactionResponse
}

func (o *TransactionOK) Error() string {
	return fmt.Sprintf("[GET /transaction/{hash}][%d] transactionOK  %+v", 200, o.Payload)
}
func (o *TransactionOK) GetPayload() *models.TransactionResponse {
	return o.Payload
}

func (o *TransactionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TransactionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransactionDefault creates a TransactionDefault with default headers values
func NewTransactionDefault(code int) *TransactionDefault {
	return &TransactionDefault{
		_statusCode: code,
	}
}

/* TransactionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type TransactionDefault struct {
	_statusCode int

	Payload *models.ErrorBody
}

// Code gets the status code for the transaction default response
func (o *TransactionDefault) Code() int {
	return o._statusCode
}

func (o *TransactionDefault) Error() string {
	return fmt.Sprintf("[GET /transaction/{hash}][%d] Transaction default  %+v", o._statusCode, o.Payload)
}
func (o *TransactionDefault) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *TransactionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
