// Code generated by "stringer -type=Type"; DO NOT EDIT.

package transaction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeSend-1]
	_ = x[TypeSellCoin-2]
	_ = x[TypeSellAllCoin-3]
	_ = x[TypeBuyCoin-4]
	_ = x[TypeCreateCoin-5]
	_ = x[TypeDeclareCandidacy-6]
	_ = x[TypeDelegate-7]
	_ = x[TypeUnbond-8]
	_ = x[TypeRedeemCheck-9]
	_ = x[TypeSetCandidateOnline-10]
	_ = x[TypeSetCandidateOffline-11]
	_ = x[TypeCreateMultisig-12]
	_ = x[TypeMultisend-13]
	_ = x[TypeEditCandidate-14]
	_ = x[TypeSetHaltBlock-15]
	_ = x[TypeRecreateCoin-16]
	_ = x[TypeEditCoinOwner-17]
	_ = x[TypeEditMultisig-18]
	_ = x[TypePriceVote-19]
	_ = x[TypeEditCandidatePublicKey-20]
	_ = x[TypeAddSwapPool-21]
	_ = x[TypeRemoveSwapPool-22]
	_ = x[TypeSellSwapPool-23]
	_ = x[TypeBuySwapPool-24]
	_ = x[TypeSellAllSwapPool-25]
	_ = x[TypeEditCommissionCandidate-26]
	_ = x[TypeMoveStake-27]
	_ = x[TypeMintToken-28]
	_ = x[TypeBurnToken-29]
	_ = x[TypeCreateToken-30]
	_ = x[TypeRecreateToken-31]
}

const _Type_name = "TypeSendTypeSellCoinTypeSellAllCoinTypeBuyCoinTypeCreateCoinTypeDeclareCandidacyTypeDelegateTypeUnbondTypeRedeemCheckTypeSetCandidateOnlineTypeSetCandidateOfflineTypeCreateMultisigTypeMultisendTypeEditCandidateTypeSetHaltBlockTypeRecreateCoinTypeEditCoinOwnerTypeEditMultisigTypePriceVoteTypeEditCandidatePublicKeyTypeAddSwapPoolTypeRemoveSwapPoolTypeSellSwapPoolTypeBuySwapPoolTypeSellAllSwapPoolTypeEditCommissionCandidateTypeMoveStakeTypeMintTokenTypeBurnTokenTypeCreateTokenTypeRecreateToken"

var _Type_index = [...]uint16{0, 8, 20, 35, 46, 60, 80, 92, 102, 117, 139, 162, 180, 193, 210, 226, 242, 259, 275, 288, 314, 329, 347, 363, 378, 397, 424, 437, 450, 463, 478, 495}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
