name: notice

on:
  release:
    types: [ published ]

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Test
        run: go test -cover ./...

      - name: Send Message in Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🥳 *NEW RELEASE!!!* 🥳

            [github.com/MinterTeam/minter-go-sdk](https://github.com/MinterTeam/minter-go-sdk) is *released* with tag [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}).
            `go get github.com/MinterTeam/minter-go-sdk/v2@${{ github.event.release.tag_name }}`

            [Changelog](https://github.com/MinterTeam/minter-go-sdk/blob/${{ github.event.release.tag_name }}/CHANGELOG.md##change-log)
